on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Run:
    name: ${{ matrix.platform }} Python ${{ matrix.python-version }} Run
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.6, 3.7, 3.8 ]
        exclude:
          - platform: macos-latest
            python-version: 3.6
          - platform: macos-latest
            python-version: 3.7
          - platform: windows-latest
            python-version: 3.6
          - platform: windows-latest
            python-version: 3.7
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Init Environment
        run: make init
      - name: Lint
        run: make flake8
      - name: Test
        run: make test
      - name: Coverage
        if: startsWith(matrix.platform, 'ubuntu') && matrix.python-version == '3.8'
        run: make coverage
      - name: Print
        run: echo "${{ github.event.ref }}"
      - name: Coverage Publish
        if: startsWith(matrix.platform, 'ubuntu') && matrix.python-version == '3.8'
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Package Publish
        if: startsWith(matrix.platform, 'ubuntu') && matrix.python-version == '3.8' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
        run:
          make publish
